// 入口文件,向外暴露工具函数

export {default as call} from './function/call'
export {apply} from './function/apply'
export {bind} from './function/bind'
export {throttle} from './function/throttle'
export {debounce} from './function/debounce'
export {map,reduce,filter,find,findIndex,every,some} from './array/delcares'
export {unique1} from './array/unique'
export {unique2} from './array/unique'
export {unique3} from './array/unique'
export {concat} from './array/concat'
export {slice} from './array/slice'
export {flatten1,flatten2} from './array/flatten'
export {compact} from './array/compact'
export {chunk} from './array/chunk'
export {difference,differences} from './array/difference'
export {merge} from './array/merge'
export {pull,pullAll} from './array/pull'
export {drop,dropRight} from './array/drap'
export {newInstance} from './object/newInstance'
export {myInstanceOf} from './object/myInstanceOf'
export {mergeObject} from './object/mergeObject'
export {clone1,clone2} from './object/clone'
export {deepClone1,deepClone2,deepClone3,deepClone4} from './object/deepClone'
export {reverseString,palindrome,truncate} from './string'
export {default as Stack} from './da/stack'
export {default as Queue} from './da/queue'
export {bubbleSort} from './sort/bubbleSort'
export {selectSort} from './sort/selectSort'
export {insertSort} from './sort/insertSort'